.all:
  tags: ["spack", "public", "aws", "x86_64"]
  image: "ghcr.io/spack/python-aws-bash:0.0.1"

.pr:
  extends: [".all"]
  only:
  - /^pr[\d]+_.*$/

.protected:
  extends: [".all"]
  only:
  - /^main$/

pr_job:
  extends: [".pr"]
  script:
    - echo "PR script - v7"

protected_job:
  extends: [".protected"]
  script:
    - echo "protected script - v7"
